[package]
name = "codec-comparison"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkyv = "0.8.12"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "codec"
harness = false
